### ISSUE TITLE
Code tags is not dark

### ISSUE THREAD

**Issue by Draeggon** [hirschan/Dark-Mode-Wikipedia#1]
The code tags like on [Python wiki](https://en.wikipedia.org/wiki/Python_(programming_language)) are white.
![image](https://user-images.githubusercontent.com/48865937/130468210-7546609f-1a57-483c-b2b3-94925f285a06.png)
I will submit a pr soon.

**Comment by hirschan** [comment]
Hey, thank you for your finding! Sounds great!
