### ISSUE TITLE
Some pages get almost covered in black

### ISSUE THREAD

**Issue by sorenss** [hirschan/Dark-Mode-Wikipedia#10]
Very happy that there's only one plugin now! But I am experiencing that certain pages get "covered" in black. It means that most of what's on the screen simply turns black (a few splitseconds after the page has loaded). It corresponds to what is in the image, so that if I scroll down, anything outside the screen is visible, but the search icon and the text just above it (login and the like) is available. The mouse still detects links and other clickable elements even though they are not visible in the black void.

It happens after I have edited a page, and on various pages that are not ordinary articles in non-English Wikipedias (e.g.  (https://da.wikipedia.org/wiki/Hj%C3%A6lp:Velkommen_til_Wikipedia]) )

**Comment by hirschan** [comment]
Thank you for your feedback and discovery! 

I am not sure if I understand correctly - certain pages gets covered in black for a few split seconds? When you say image, do you mean the Wikipedia image (the one I attached below)?
![wikipedia_image](https://user-images.githubusercontent.com/45165564/147387830-134c2a17-7cf0-4549-b6de-87227a122786.png)

Right now, the extension is based for English Wikipedia (en.wikipedia) and it is not optimal for the editing pages right now. Do you have any screenshots that demonstrates what you mean? 

Tack på förhand :-)

**Comment by sorenss** [comment]
It's after a split second and it keeps staying. I think my "image" should have been "screen". The Wikipedia logo disappears completely. But here's a screenshot:

![image](https://user-images.githubusercontent.com/89091409/147392239-a28916f8-e6c7-4910-93e1-f7f02b18996c.png)

But if I scroll down, anything below the "top screen" (I'm not completely sure what to call it) is visible. Screenshot of the same page as above but scrolled a bit down:

![image](https://user-images.githubusercontent.com/89091409/147392280-16e907a8-2673-4b2a-8fee-f402d1f484df.png)

It's minor but very weird. When it happens after editing, I can just reload. I have a feeling it did happen on some special pages, but can't find them now. I will return if I figure out if I remember right.

**Comment by hirschan** [comment]
I tried following and got the same issue as you:

_Edit a page_ -> _publish the page_ -> _everything is black/invincible on the screen_ 

If you **refresh** the page it disappears, but this is quite a weird bug I must say. I will try to look into it, I literally have no idea why it happens.

**Comment by hirschan** [comment]
I tried YtaloWill's  [dark mode](https://addons.mozilla.org/sv-SE/firefox/addon/wikipedia-dark-theme/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) extension and the same issue occurs. Seems to be an issue when you have a CSS extension.

**Comment by sorenss** [comment]
Oh well. But thanks for looking into it. Let me know if there's more I can do

**Comment by hirschan** [comment]
Forgot to ask: what version of Firefox are you running on? And is it on Windows, Linux?

**Comment by hirschan** [comment]
I believe I identified the problem: it is the div element. I might have a workaround, will update these coming days.

**Comment by sorenss** [comment]
Sorry for my delay. I use it on both Windows and Linux, but I can confirm that it has been fixed now! Thank you very much!
