### ISSUE TITLE
Font color is too bright

### ISSUE THREAD

**Issue by andersfylling** [hirschan/Dark-Mode-Wikipedia#11]
I've noticed some fatigue using this plugin, related to the color contrast of the background and letters. Issue seem to be that the font is simply too bright, with a value of `#fff`. 

Could the font color be adjusted to say `#c9d1d9 ` ? This is the same color used by github for the README.md preview, which I find a bit more soothing.

**Comment by hirschan** [comment]
Hi andersfylling, thank you for submitting your feedback. Great input and idea - will update!
