### ISSUE TITLE
LaTeX appears black.

### ISSUE THREAD

**Issue by jjderooy** [hirschan/Dark-Mode-Wikipedia#14]
Hello. I am running Firefox 95.0.2 on arch Linux.

LaTeX is appearing as its default black font making it almost invisible against the dark background that the extension creates. For example the wiki page on factorial without the extension appears as expected:
![image](https://user-images.githubusercontent.com/59892080/147867437-e1d213eb-f353-4aa4-bd3b-368d9da4cae7.png)

With the extension however:
![image](https://user-images.githubusercontent.com/59892080/147867364-0f9dcd2f-ab7d-441e-a373-6cd6eaac09e8.png)

This makes the extension pretty unusable for most science and mathematics related articles as LaTeX is so ubiquitous. Otherwise the extension is fantastic.

Thanks!

**Comment by hirschan** [comment]
Hi, thank you for your finding! These formulas are posted as images (with black text) and my **only option** is to change the background color to dark grey:

![Screenshot 2022-01-02 at 11-45-43 Factorial - Wikipedia](https://user-images.githubusercontent.com/45165564/147873381-ed74cfcf-335e-48be-9353-8f9858a51ae4.png)

I hope the coloring is okay for you, if not let me know. I will update the extension shortly :-)

**Comment by jjderooy** [comment]
Hi @hirschan. I decided to try fixing the issue myself and made a PR. I hope that's ok and you haven't already spent time fixing it yourself. The change I made adjusts the font color to white rather than changing the background color as you suggested.
