### ISSUE TITLE
Low rating? (temporary)

### ISSUE THREAD

**Issue by hirschan** [hirschan/Dark-Mode-Wikipedia#16]
Hi @KAMiKAZOW! I saw that you rated the extension (thank you for doing so). I would like to know why you gave it a low rating so I can improve it :-)

**Comment by KAMiKAZOW** [comment]
Because your Extension makes Wikipedia unusable. How is anybody supposed to read anything here?
![image](https://user-images.githubusercontent.com/3259076/152573693-31f0b720-0041-4483-9bb4-ecd8b6b63019.png)

**Comment by KAMiKAZOW** [comment]
I found there's a Dark Mode under Gadgets, so your extension is useless anyway.

**Comment by sorenss** [comment]
The Dark Mode gadget is not available for all languages (and it's only for users with an acount, right?). It's true that the grey-on-white is not ideal, but it occurs outside of normal articles.

**Comment by hirschan** [comment]
I just fixed it, will include in next release: 
![Screenshot 2022-02-05 at 11-34-16 Preferences - Wikipedia](https://user-images.githubusercontent.com/45165564/152638576-1b365228-dba2-46be-a2a0-7698d851629b.png)

IThat's not true @KAMiKAZOW - the Gadget is only available for **users** which means that this extension is not useless.

**Comment by KAMiKAZOW** [comment]
Look, I rated the extension the way it worked for me or more precisely how it did not.

I got tagged though online stalking, so just leave me alone if you don't agree. I did not look to be involved with this extension on GitHub.

**Comment by hirschan** [comment]
I understand your point of view, sorry for bothering you. Just wanted the feedback
