### ISSUE TITLE
Feature suggestion: quick search

### ISSUE THREAD

**Issue by hirschan** [hirschan/Dark-Mode-Wikipedia#18]
I have thought about a feature pleasant for us who use Wikipedia on a daily basis. Instead of opening a Wikipedia browser and manually search you can now **right-click** on highlighted text and open in a new Wikipedia tab instantly.

Demonstration:
![right-clicked](https://user-images.githubusercontent.com/45165564/155403048-9e69f399-b1f6-4ac2-99b1-9588a7854e61.png)

Right now it only works on the Wikipedia domain (```://*.wikipedia.org/*```) but I want to expand it for all websites (```"http://*/*", "https://*/*"```). For example, let's say you are browsing a news website and you want to highlight a specific term or word(s) to search for on Wikipedia.

I will publish a PR later. Any thoughts, suggestions or improvements about this @Draeggon, @Mounster-Chef, @jjderooy? I hope you are fine with being tagged and slightly involved in this project, otherwise let me know 😄

**Comment by jjderooy** [comment]
I would definitely use that feature so if can be implemented and works reliably enough I say go for.

**Comment by hirschan** [comment]
Still researching about it, right now it only works for Wikipedia domain or all domains (this applies to the css as well). The issue is the ```manifest.json``` file and its declaration of domains to apply to. In worst case I'll have to create a **separate** extension for this specific feature suggestion.

**Comment by hirschan** [comment]
Solved, will update on Firefox soon.
