### ISSUE TITLE
The Quick Search feature should really be its own separate addon

### ISSUE THREAD

**Issue by Nekkowe** [hirschan/Dark-Mode-Wikipedia#20]
When I got a notification that Dark Mode Wikipedia now wanted to "Access data for all websites" and "Access browser tabs", I thought it'd been hijacked by some shady data mining scheme until I looked at the updated Readme file.

The functionality from issue #18 is neat, but separate from the purpose people use this addon for.
It's a useful function that deserves its own addon, and at the same time, should not be inherently tied to this one.

**Comment by hirschan** [comment]
Hi, thank you for posting your feedback! 

I will be away for a few days now but I can take a look at this when I return. 

My initial thought is: do people prefer having many addons with minor functionalities or one addon "to rule them all"?

**Comment by Nekkowe** [comment]
Personally, I definitely prefer the former!

Some few addons do style themselves as big overhauls for specific websites (usually social media sites), addressing many common gripes at once, but the vast majority I've seen (and use) are single-purpose. 

This modularity helps keep individual addons lightweight in terms of performance - people seem to usually seek out addons to address specific needs or qualms. 

For instance, people looking to view Wikipedia in Dark Mode generally won't expect - or necessarily want - an extra entry in their context menu, or to give a single addon permission to access data on all sites.

**Comment by hirschan** [comment]
Great input - maybe it's better to strive for the single responsibility purpose here. I will try to work on this these coming days :)

**Comment by Nekkowe** [comment]
Thank you very much!

**Comment by hirschan** [comment]
@Nekkowe created a new repo for quick search, will upload to Firefox soon: https://github.com/hirschan/Quick-Search-Wikipedia
