### ISSUE TITLE
UI: Gradient white color on side menu

### ISSUE THREAD

**Issue by hirschan** [hirschan/Dark-Mode-Wikipedia#27]
I noticed this gradient coloring on the side menu and need to find a way to re-color it since I find it ugly. Looks like it might be something with `div` elements using `::after` selector 🤔 

![side_menu](https://user-images.githubusercontent.com/45165564/222967495-def2cb4e-bd2b-4948-ad6c-306f885beca5.png)

**Comment by cjohn-afk** [comment]
Hello I have no way to contact you other than this, I can continue to fix things and help with this extension but I need the permissions to create branches so I don't have to fork it every time. :)

**Comment by hirschan** [comment]
Hey @cjohn-afk, just sent you an invite to the repository :) 

I guess that should fix it? If not, please let me know!

**Comment by hirschan** [comment]
Any updates @cjohn-afk? :)
