### ISSUE TITLE
UI: White line cut

### ISSUE THREAD

**Issue by hirschan** [hirschan/Dark-Mode-Wikipedia#28]
Another UI glitch bothering me is this white line is being colored to dark which makes it cut, see screenshot below:
![white_line_cut](https://user-images.githubusercontent.com/45165564/222967620-be09b352-2b96-4a7b-b4ea-c24baef460d5.png)

**Comment by cjohn-afk** [comment]
Fixed in #30

**Comment by hirschan** [comment]
Just realized this became an issue again, guessing Wikipedia did some updates 🤔

**Comment by hirschan** [comment]
This time it's the upper part instead of the line below 😅 

![white cut line upper](https://github.com/hirschan/Dark-Mode-Wikipedia/assets/45165564/9b237a71-ed35-4f5d-aecc-3874811a308e)

**Comment by hirschan** [comment]
Fixed in PR: https://github.com/hirschan/Dark-Mode-Wikipedia/commit/f4b11e5e870864033fe3688e65bc94805f6a9553
