### ISSUE TITLE
Add options for color

### ISSUE THREAD

**Issue by Draeggon** [hirschan/Dark-Mode-Wikipedia#3]
I think i would be cool if there were some options [(mozilla ref)](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Implement_a_settings_page) to tweak the color to everyone taste, with some color html input and css variables.
What do you think about it ?

And btw thank you for the wall of fame.

**Comment by hirschan** [comment]
That would be awesome! Unfortunately I am a bit busy these days with school. I also have issue to update the Firefox extension due to authentication blocking me - so I will have to solve that ASAP.

**Comment by Draeggon** [comment]
Okay in that case i will try to do a pr.

**Comment by hirschan** [comment]
What do you think of having pre-configured color themes? And if people want to create their own they can customize and save as a "template" or so?

**Comment by hirschan** [comment]
Created a new branch for this feature, see README for an idea of how we could implement it: https://github.com/hirschan/Dark-Mode-Wikipedia/tree/customize-colors

**Comment by Draeggon** [comment]
I think it would be great to have a "template" system as you stated. I will add a few things on the branch soon.

**Comment by hirschan** [comment]
No worries, take your time mate! Btw I have accidently locked myself out from logging in to Firefox (2fa)... So I am considering if I should upload this as a "new" extension with a new account.

**Comment by hirschan** [comment]
Entire UI is in place now! Great job, I added all 6 colors groups after your PR.

**Comment by Draeggon** [comment]
@hirschan have you been able to log back in ?

**Comment by hirschan** [comment]
Speaking of something else - @Draeggon I managed to restore my old account. I will upload all updates on the original Dark Mode Wiki on Firefox. See the README.

**Comment by Draeggon** [comment]
Nice

**Comment by hirschan** [comment]
Hi @Draeggon, still game on trying to fix this together? :)
