### ISSUE TITLE
"Read Wikipedia in your Language" button colored white

### ISSUE THREAD

**Issue by TeaCows** [hirschan/Dark-Mode-Wikipedia#31]
_Before Clicking_
![Before Clicking](https://user-images.githubusercontent.com/63617135/224812295-d249af54-9fe7-49de-9448-2f0f44ad0cc4.png)
_After Clicking_
![After Clicking](https://user-images.githubusercontent.com/63617135/224812558-3cb0ebec-4d72-41d6-841e-a44f6d69a6da.png)
***
The button and button text are incorrectly colored white and gray.

**Comment by hirschan** [comment]
Good catch! I noticed the same with the search button in the top.

![search_button](https://user-images.githubusercontent.com/45165564/224826369-601d98fd-3815-4ec7-9dfe-bbbff96d08a2.png)

**Comment by cjohn-afk** [comment]
Issue fixed in [b253640](https://github.com/hirschan/Dark-Mode-Wikipedia/commit/b253640c5986f5f1aab1c01bae651ffe8afef1a3)
