### ISSUE TITLE
Feature request: full width

### ISSUE THREAD

**Issue by J-Siu** [hirschan/Dark-Mode-Wikipedia#34]
I would like to see option to enable article to be full width. This will be very useful. Thank you!!

**Comment by hirschan** [comment]
Hi @J-Siu, thank you for your request. Can you elaborate? For me full width works fine:
![full_width](https://github.com/hirschan/Dark-Mode-Wikipedia/assets/45165564/a45aa72e-37ed-4628-94c9-87666a37130c)

**Comment by J-Siu** [comment]
Oh .... I don't know that button exist🤦‍♂️
My bad, closing this now.
