### ISSUE TITLE
Partially white theme on Wikipedia after 2023-11-04 update

### ISSUE THREAD

**Issue by verlorener** [hirschan/Dark-Mode-Wikipedia#39]
Good day, I noticed that Wiki page has been broken after update 2023-11-04
Firefox 119.0 (64-bit)
Win10

![image](https://github.com/hirschan/Dark-Mode-Wikipedia/assets/11644764/a5ba29ec-98a4-4219-af0c-c429bcb52159)

**Comment by verlorener** [comment]
After downgrading to 4.4.5 page show was fixed

**Comment by hirschan** [comment]
Thank you for noticing, quick fix coming up 🚀

**Comment by hirschan** [comment]
Can you send me the link?

**Comment by hirschan** [comment]
Think I found the issue, forgot to include: `div.content` element, can you please verify it works now with 4.4.7? Thanks for informing me!

**Comment by verlorener** [comment]
@hirschan Looks like for 4.4.8. there is no problems, the issue should be closed.
Thank you for saving eyes 🤝
