### ISSUE TITLE
White items with version 4.4.8

### ISSUE THREAD

**Issue by MDawg957** [hirschan/Dark-Mode-Wikipedia#40]
Noticing this with 4.4.8, first link has white in the table for episodes, second pair of images are issues with text visibility on the sidebar

Firefox 119.0 x64

https://en.wikipedia.org/wiki/List_of_Tenchi_Muyo!_Ryo-Ohki_episodes

![image](https://github.com/hirschan/Dark-Mode-Wikipedia/assets/12445509/c8071891-7f18-4099-9712-c4b011d09a5b)

https://en.wikipedia.org/wiki/Tenchi_Muyo!_Ryo-Ohki

![image](https://github.com/hirschan/Dark-Mode-Wikipedia/assets/12445509/d44d3c09-7c63-45e2-b48e-724315af90d7)

![image](https://github.com/hirschan/Dark-Mode-Wikipedia/assets/12445509/066e8e88-1bac-4f18-ab2c-f05c01d4f340)

**Comment by hirschan** [comment]
Thank you so much, tables are tricky and I will work on it the coming days 🚀

**Comment by hirschan** [comment]
Fixed in 4.4.9, let me know if it works 💯

**Comment by MDawg957** [comment]
The table issue from the episode list is fixed. Thank you. 

The sidebar is readable now but I'm wondering there should be some sort of coloring on the fields in the sidebar. With light mode it's there, but the fixed dark mode completely removes it

https://en.wikipedia.org/wiki/Tenchi_Muyo!_Ryo-Ohki

![image](https://github.com/hirschan/Dark-Mode-Wikipedia/assets/12445509/bcb3f88a-0192-4bd7-91c2-0c40ac777841)
![image](https://github.com/hirschan/Dark-Mode-Wikipedia/assets/12445509/c66ff905-7251-493a-a5d3-cc72f1d6f9ae)

**Comment by hirschan** [comment]
> The table issue from the episode list is fixed. Thank you.
> 
> The sidebar is readable now but I'm wondering there should be some sort of coloring on the fields in the sidebar. With light mode it's there, but the fixed dark mode completely removes it
> 
> https://en.wikipedia.org/wiki/Tenchi_Muyo!_Ryo-Ohki
> 
> ![image](https://user-images.githubusercontent.com/12445509/280559663-bcb3f88a-0192-4bd7-91c2-0c40ac777841.png) ![image](https://user-images.githubusercontent.com/12445509/280559698-c66ff905-7251-493a-a5d3-cc72f1d6f9ae.png)

I see your point, however it is difficult to color certain bars because it might override somewhere else which makes this extension quite tricky to maintain 😅 I will think about it and see what I can do in the near future! 🚀
