### ISSUE TITLE
Blanks on pages when using certain Firefox features

### ISSUE THREAD

**Issue by MDawg957** [hirschan/Dark-Mode-Wikipedia#41]
This is a minor thing I've been noticing with the extension for over a year but when using this with the [Foxy Gestures](https://addons.mozilla.org/firefox/addon/foxy-gestures/) extension in Firefox, if you do any gesture nav on Wikipedia, it blanks out the page. It clears up as soon as you stop doing any gesture nav, but on any normal website, this does not happen. Not sure what it would take to fix this.

**Comment by MDawg957** [comment]
I noticed this problem also happens when you use the built-in screenshot feature in Firefox. Right-click and then choosing Take Screenshot causes a blanking out the Wikipedia page you're on.

![image](https://github.com/hirschan/Dark-Mode-Wikipedia/assets/12445509/2faae84d-b56d-4faa-872d-da015d2948df)

**Comment by hirschan** [comment]
Thank you for submitting, will investigate! 👀

**Comment by hirschan** [comment]
> I noticed this problem also happens when you use the built-in screenshot feature in Firefox. Right-click and then choosing Take Screenshot causes a blanking out the Wikipedia page you're on.
> 
> ![image](https://user-images.githubusercontent.com/12445509/280559797-2faae84d-b56d-4faa-872d-da015d2948df.png)

Found issue, I forgot to add element: `iframe` as excluded from dark coloring. Will include in 4.5.0 update 🚀

**Comment by hirschan** [comment]
Can you explain how this Foxy Gestures work? How can I reproduce your bug? Any commands? I barely know what it is.

**Comment by MDawg957** [comment]
> Can you explain how this Foxy Gestures work? How can I reproduce your bug? Any commands? I barely know what it is.

Foxy Gestures is gesture navigation for your browser. So like I can hold down the right mouse button to activate and then drag to my left and it takes me back a previous page. Same to the right would take me forward. They have multiple commands and you can make your own custom ones, but the idea is just being able to do what you want in the browser with your mouse and not clicking in the UI.



> > I noticed this problem also happens when you use the built-in screenshot feature in Firefox. Right-click and then choosing Take Screenshot causes a blanking out the Wikipedia page you're on.
> > ![image](https://user-images.githubusercontent.com/12445509/280559797-2faae84d-b56d-4faa-872d-da015d2948df.png)
> 
> Found issue, I forgot to add element: `iframe` as excluded from dark coloring. Will include in 4.5.0 update 🚀

Confirmed as fixed. Thank you for being so quick about looking at these!

**Comment by hirschan** [comment]
> > Can you explain how this Foxy Gestures work? How can I reproduce your bug? Any commands? I barely know what it is.
> 
> Foxy Gestures is gesture navigation for your browser. So like I can hold down the right mouse button to activate and then drag to my left and it takes me back a previous page. Same to the right would take me forward. They have multiple commands and you can make your own custom ones, but the idea is just being able to do what you want in the browser with your mouse and not clicking in the UI.
> 
> > > I noticed this problem also happens when you use the built-in screenshot feature in Firefox. Right-click and then choosing Take Screenshot causes a blanking out the Wikipedia page you're on.
> > > ![image](https://user-images.githubusercontent.com/12445509/280559797-2faae84d-b56d-4faa-872d-da015d2948df.png)
> > 
> > 
> > Found issue, I forgot to add element: `iframe` as excluded from dark coloring. Will include in 4.5.0 update 🚀
> 
> Confirmed as fixed. Thank you for being so quick about looking at these!

Thank you for explaining, I found the issue :) I'll update soon again to fix Foxy Gesture compatibility for 4.5.1, missed `canvas` element!
