### ISSUE TITLE
Red links (indicating yet-to-be-created articles) show up as blue.

### ISSUE THREAD

**Issue by awawe** [hirschan/Dark-Mode-Wikipedia#43]
It's impossible to tell the difference between real articles and non-existent ones, while using the extension with legacy vector.

![__1](https://github.com/hirschan/Dark-Mode-Wikipedia/assets/44501060/16ede348-2660-4109-9517-27fcc2016924)
![image](https://github.com/hirschan/Dark-Mode-Wikipedia/assets/44501060/5b7d6756-83bd-4a6e-8338-1e29ffb97981)

**Comment by hirschan** [comment]
Update the extension, it works with latest update 👍
