### ISSUE TITLE
Normal text is too dark.

### ISSUE THREAD

**Issue by VoidedWinter** [hirschan/Dark-Mode-Wikipedia#44]
Title.  It didn't start out this dark and I've no idea what changed.  Running the most recent version of the extension on Firefox 119.0.1 under Kubuntu 20.04LTS, non-snap version. 
![image](https://github.com/hirschan/Dark-Mode-Wikipedia/assets/18587771/51162e35-e3b8-47e9-b0d1-49683f82f4f9)

As you can see, totally unreadable, even in a completely dark room.

**Comment by hirschan** [comment]
First off, thank you for submitting! I apologize for the unpleasant UI. 

Secondly, I suspect the js script is not running on your browser or it cannot find the elements it's looking for in the DOM. 

Is it like this for all your Wiki pages?

I can confirm it works for me, but I will need to investigate this. Please be patient as I'm having a busy life right now :)
![bitters](https://github.com/hirschan/Dark-Mode-Wikipedia/assets/45165564/b1b28cee-6366-4cca-a285-115841d5a8db)

**Comment by VoidedWinter** [comment]
You had me at "script not running in your browser".  I use an extension that pretty much blocks java.  Added wikipedia to the whitelist, done deal.  Thanks and sorry to bother you for something so trivial.
