### ISSUE TITLE
Unreadable text due to table colors

### ISSUE THREAD

**Issue by MDawg957** [hirschan/Dark-Mode-Wikipedia#46]
Extension version: 4.5.2
Firefox 120.0.1 (64-bit)

https://en.wikipedia.org/wiki/List_of_American_films_of_2023

Text on some of the tables is hard or impossible to read due to coloring.

![image](https://github.com/hirschan/Dark-Mode-Wikipedia/assets/12445509/4a11d81e-6138-4994-bacf-0f88bf66f05e)
![image](https://github.com/hirschan/Dark-Mode-Wikipedia/assets/12445509/8e931823-9e1b-4683-9ddc-088968838f67)

**Comment by hirschan** [comment]
Thanks, will fix. This is part of issue #21

**Comment by hirschan** [comment]
Fixed in commit: 452e24b42b09edd52393befad23cbf3232f8977c

Will update version, 4.5.3 🚀
