### ISSUE TITLE
Version 4.5.3; unreadable text color

### ISSUE THREAD

**Issue by MMachado05** [hirschan/Dark-Mode-Wikipedia#48]
Version 4.5.3, as of the writing of this issue, does not correctly render most text on a Wikipedia page.

![image](https://github.com/hirschan/Dark-Mode-Wikipedia/assets/111894108/e704f88d-d8c1-42da-b400-7ca0211aa518)

**Comment by hirschan** [comment]
Hi, thanks for submitting! Someone else reported this issue too and fixed it, please let me know if this helps you: https://github.com/hirschan/Dark-Mode-Wikipedia/issues/44

**Comment by MMachado05** [comment]
It does! Thank you so much.

For anyone in the future; uBlock might disallow certain JS scripts from running, so just whitelist Wikipedia.
