### ISSUE TITLE
Media Viewer layout has been updated, arrows and icons not viewable in media viewer

### ISSUE THREAD

**Issue by yee-bit** [hirschan/Dark-Mode-Wikipedia#50]
The media viewer layout has been updated by Wikipedia and the icons such as arrows and exit icon are not visible. An update would be nice, thanks :)

![image](https://github.com/hirschan/Dark-Mode-Wikipedia/assets/81834767/4d1f1ea1-b981-4445-b324-aefd9858b974)

That is what it looks like without the extension enabled.

![image](https://github.com/hirschan/Dark-Mode-Wikipedia/assets/81834767/374c9bb0-0478-4d2a-a2b8-e86e43db35d9)

As you can see, none of the icons are visible with the extension enabled.

**Comment by hirschan** [comment]
Thanks, will have a look the coming days! :)

**Comment by hirschan** [comment]
Fixed, will publish soon 🚀 
<img width="1271" alt="grey btns" src="https://github.com/hirschan/Dark-Mode-Wikipedia/assets/45165564/ee7927cc-6900-4b48-99b6-0740cd3a80e1">
