### ISSUE TITLE
Almost invisable chemical structures

### ISSUE THREAD

**Issue by gokibhc** [hirschan/Dark-Mode-Wikipedia#52]
Mostly on pages with chemical structures the molecular structure is virtually invisable because it's a .png file with a transparent background and the structure is also black. So it's black on black and mostly unrecognizable. Added pictures from one random page. I included german and english but presumably it's on all languages. Minor issue and I have no idea about coding so I also have no idea on going on about this. Just wanted to point it out as it has irritated me while working.
![Unbenannt](https://github.com/hirschan/Dark-Mode-Wikipedia/assets/170556839/52ac1e8f-8d4c-4129-8267-c4d2332f315c)
![Unbenannt1](https://github.com/hirschan/Dark-Mode-Wikipedia/assets/170556839/7427fa95-48c0-481f-b8a5-f57ced9b8391)

**Comment by hirschan** [comment]
Thank you for reporting! Will have a look :)

**Comment by hirschan** [comment]
I've found a workaround: I can color `svg.png` files with a lighter dark grey background, see screenshot. It's not perfect, but this is as good as it gets for now. What do you think? :)

<img width="210" alt="light_grey" src="https://github.com/hirschan/Dark-Mode-Wikipedia/assets/45165564/c3c4c94a-b874-40a1-8d51-960226bc9108">

**Comment by gokibhc** [comment]
I found another page where some structurs are more greyish and more distinguishable but most are still black and virtually invisable. Heres the link: https://de.wikipedia.org/wiki/Droge#Klassifizierung
![Unbenannt](https://github.com/hirschan/Dark-Mode-Wikipedia/assets/170556839/194e17b6-b637-4f41-a287-856b9769d5e8)

**Comment by hirschan** [comment]
Perfect, will have a look and release new version the coming days!
