### ISSUE TITLE
Syntax highlight colours shown as white

### ISSUE THREAD

**Issue by Mounster-Chef** [hirschan/Dark-Mode-Wikipedia#6]
The colours of the words in the code markdown get overriden to white/grey.
Original highlighting:
![imagen](https://user-images.githubusercontent.com/60630177/137015482-26ab0299-1a6c-4a73-b915-ae58a8a61997.png)
When dark mode is switched on:
![imagen](https://user-images.githubusercontent.com/60630177/137014944-35404b03-2279-42de-861c-5d61990594db.png)

**Comment by hirschan** [comment]
Fixed now, pushed to master. I will update the Firefox extension soon, you can download locally, load manifest.json and check out this page: https://en.wikipedia.org/wiki/%22Hello,_World!%22_program#Examples
