### ISSUE TITLE
Custom colours in tables are overridden

### ISSUE THREAD

**Issue by Mounster-Chef** [hirschan/Dark-Mode-Wikipedia#8]
Custom colours like the ones in tables are overridden to the brackground colour.
Originally:
![imagen](https://user-images.githubusercontent.com/60630177/139847274-50ab729e-a4cb-43b0-8e20-ecfed35011eb.png)

Dark mode:
![imagen](https://user-images.githubusercontent.com/60630177/139847235-f3403ec2-acac-47de-9a01-d724a383769b.png)

[Article for reference](https://es.wikipedia.org/wiki/King_Crimson#Componentes_del_grupo_por_%C3%A1lbumes)

**Comment by hirschan** [comment]
Thank you for posting, will look into this later probably.

**Comment by hirschan** [comment]
Not sure how I can solve it. Maybe you have some idea @Draeggon ?
